"""add character catalog resources

Revision ID: 1240a4fcfcbc
Revises: b3f9c07ae214
Create Date: 2026-08-21 13:02:33.475009

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1240a4fcfcbc"
down_revision: str | Sequence[str] | None = "b3f9c07ae214"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset_resources",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("asset_id", sa.String(length=36), nullable=False),
        sa.Column("resource_key", sa.String(length=300), nullable=False),
        sa.Column("origin", sa.String(length=32), nullable=False),
        sa.Column("media_type", sa.String(length=16), nullable=False),
        sa.Column("mime_type", sa.String(length=120), nullable=True),
        sa.Column("path", sa.String(length=500), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("byte_size", sa.BigInteger(), nullable=True),
        sa.Column("revision", sa.String(length=200), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("source_fields_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("media_type IN ('image', 'audio')", name="ck_asset_resource_media_type"),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_id", "resource_key", name="uq_asset_resource_key"),
    )
    with op.batch_alter_table("asset_resources", schema=None) as batch_op:
        batch_op.create_index("ix_asset_resource_asset_media", ["asset_id", "media_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_asset_resources_asset_id"), ["asset_id"], unique=False)

    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("external_source", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("external_id", sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column("voice_id", sa.String(length=200), nullable=True))
        batch_op.create_index("ix_asset_external_identity", ["external_source", "external_id"], unique=False)
        batch_op.create_unique_constraint("uq_asset_external_identity", ["external_source", "external_id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.drop_constraint("uq_asset_external_identity", type_="unique")
        batch_op.drop_index("ix_asset_external_identity")
        batch_op.drop_column("voice_id")
        batch_op.drop_column("external_id")
        batch_op.drop_column("external_source")

    with op.batch_alter_table("asset_resources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_asset_resources_asset_id"))
        batch_op.drop_index("ix_asset_resource_asset_media")

    op.drop_table("asset_resources")
    # ### end Alembic commands ###
